version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directories:
    - /cmd/aws
    - /cmd/aws/ci
    - /cmd/gcp
    - /cmd/gcp/ci
    - /cmd/gcp/staging
    - /internal/hammer
    - /internal/hammer/ci
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"
